# Generated by Django 4.2.6 on 2023-10-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per day')),
                ('trial_days', models.PositiveIntegerField(default=0, verbose_name='Trial days')),
                ('max_jobs', models.PositiveIntegerField(default=0, verbose_name='Max jobs')),
                ('is_default', models.BooleanField(default=False, help_text='If this plan is default, it will be assigned to new users.', verbose_name='Is default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_fallback', models.BooleanField(default=False, help_text='If this plan is fallback, it will be assigned to users who have no active plan.', verbose_name='Is fallback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('weight', models.PositiveIntegerField(default=0, help_text='Plans with higher weight will be shown first.', verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ('weight', 'id'),
            },
        ),
    ]
